# Generated by Django 4.0.4 on 2022-04-21 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('floraison', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('starting_price', models.FloatField()),
                ('message', models.CharField(max_length=50)),
                ('days_required', models.IntegerField(max_length=3)),
                ('published', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user_address',
            name='contact_phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user_address',
            name='postal',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='order_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.FloatField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floraison.item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floraison.order')),
            ],
        ),
    ]
