# Generated by Django 4.0.4 on 2022-04-21 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('floraison', '0003_alter_item_days_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='cake_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='floraison.cake_type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='floraison.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='cookie_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='floraison.cookie_type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='filling',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='floraison.filling'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='frosting',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='floraison.frosting'),
            preserve_default=False,
        ),
    ]
