# Generated by Django 4.0.4 on 2022-04-21 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floraison', '0004_item_cake_type_item_category_item_cookie_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='user_address',
            options={'verbose_name_plural': 'Addresses'},
        ),
        migrations.RemoveField(
            model_name='item',
            name='message',
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.CharField(default='Description coming soon!', max_length=200),
            preserve_default=False,
        ),
    ]
