# Generated by Django 4.0.4 on 2022-04-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floraison', '0007_remove_user_address_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_item',
            name='message',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order_item',
            name='special_instructions',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
