# Generated by Django 4.0.4 on 2022-04-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floraison', '0008_order_item_message_order_item_special_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.FileField(default='No image yet!', upload_to='./images/'),
            preserve_default=False,
        ),
    ]
