# Generated by Django 4.0.4 on 2022-04-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floraison', '0010_alter_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='photo',
            field=models.ImageField(default='none', upload_to='images/'),
        ),
    ]
