# Generated by Django 4.0.4 on 2022-04-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floraison', '0012_remove_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='photo',
            field=models.ImageField(default='../media/images/nbc-tech.png', upload_to='images/'),
        ),
    ]
