# Generated by Django 4.0.4 on 2022-04-30 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floraison', '0013_alter_item_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookie_type',
            name='image',
            field=models.ImageField(default='../media/images/nbc-tech.png', upload_to=''),
        ),
    ]
