# Generated by Django 4.0.4 on 2022-04-30 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floraison', '0014_cookie_type_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookie_type',
            name='description',
            field=models.CharField(default='No description yet!', max_length=200),
        ),
    ]
