# Generated by Django 4.0.4 on 2022-04-30 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floraison', '0015_cookie_type_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookie_type',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
