# Generated by Django 4.0.4 on 2022-04-30 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('floraison', '0016_alter_cookie_type_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='cookie_type',
        ),
    ]
