# Generated by Django 4.0.4 on 2022-05-01 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floraison', '0017_remove_item_cookie_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery',
        ),
        migrations.AlterField(
            model_name='order',
            name='due_date',
            field=models.DateTimeField(default=False),
        ),
    ]
