# Generated by Django 4.0.4 on 2022-05-03 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('floraison', '0019_alter_order_due_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_item',
            old_name='order',
            new_name='Order',
        ),
    ]
